apiVersion: apps/v1
kind: Deployment
metadata:
  name: messages
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messages
  template:
    metadata:
      labels:
        app: messages
      annotations:
        linkerd.io/inject: enabled
        config.linkerd.io/proxy-await: "enabled"
    spec:
      containers:
        - name: messages
          image: thsjowi/messages:1.0.9
          imagePullPolicy: Always
          ports:
            - containerPort: 8086
          env:
            - name: SERVER_PORT
              value: "8086"

            # Cassandra Configuration
            - name: CASSANDRA_HOST
              value: "cassandra"
            - name: CASSANDRA_PORT
              value: "9042"
            - name: CASSANDRA_DATACENTER
              value: "DC1"
            - name: CASSANDRA_KEYSPACE
              value: "messaging"
            - name: CASSANDRA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: cassandra-username
            - name: CASSANDRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: cassandra-password

            # Kafka Configuration
            - name: KAFKA_HOST
              value: "kafka"
            - name: KAFKA_PORT
              value: "9092"
            - name: KAFKA_GROUP_ID
              value: "messages-service"
