apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:

  # Database
  db-port: "YOUR_DB_PORT"
  db-username: "YOUR_DB_USERNAME"
  db-password: "YOUR_DB_PASSWORD"
  
  # Redis/KeyDB
  redis-port: "6379"
  redis-password: "" 
  # Kafka
  kafka-host: kafka-bootstrap
  kafka-port: "9092"

  # Cassandra
  cassandra-username: "YOUR_CASSANDRA_USERNAME"
  cassandra-password: "YOUR_CASSANDRA_PASSWORD"
  
  # Vault
  vault-host: "YOUR_VAULT_IP"
  vault-port: "8200"
  vault-token: "YOUR_VAULT_TOKEN"
  
  # JWT
  jwt-secret: "YOUR_JWT_SECRET_KEY"

  # Mail
  mail-username: "YOUR_MAIL_USERNAME"
  mail-password: "YOUR_MAIL_PASSWORD"
  mail-sender-email: "YOUR_SENDER_EMAIL"
  mail-sender-name: "YOUR_SENDER_NAME"


  # Google OAuth
  google-client-id: "your-google-client-id"
  google-client-secret: "your-google-client-secret"

  # GitHub OAuth
  github-client-id: "your-github-client-id"
  github-client-secret: "your-github-client-secret"